version: 0.0
os: linux

files:
  - source: /client/build/
    destination: /staging/my-subreddit-instance-fe
    pattern: "**"

hooks:
  AfterInstall:
    - location: client/scripts/after_install
      timeout: 300
      runas: root
