version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - yum update -y
      - yum install -y nodejs

  pre_build:
    commands:
      - npm --version

  build:
    commands:
      # - dotnet publish src/my-subreddit-instance.csproj -o build
      - npm i --prefix client
      - npm run build --prefix client

  post_build:
    commands:
      - cd client
      - cp appspec.yml build/appspec.yml
      - cp scripts build/scripts
      - cd client/build
      - zip -r my-subreddit-instanct-fe.zip .
      - mv my-subreddit-instanct-fe.zip ../../my-subreddit-instanct-fe.zip
      - cd ../../

artifacts:
  files:
    # - "my-subreddit-instance.zip"
    - "my-subreddit-instanct-fe.zip"
