version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - yum update -y
      - yum install -y nodejs

  pre_build:
    commands:
      - npm --version

  build:
    commands:
      # - dotnet publish src/my-subreddit-instance.csproj -o build
      - npm i --prefix client
      - npm run build --prefix client

  post_build:
    commands:
      - cp client appspec.yml ./
      - zip -r my-subreddit-instance-fe.zip client/build/ appspec.yml client/scripts/

artifacts:
  files:
    # - "my-subreddit-instance.zip"
    - "my-subreddit-instance-fe.zip"
