version: 0.0
os: linux

files:
  - source: /my-subreddit-instance.conf
    destination: /etc/nginx/conf.d/
  - source: /my-subreddit-instance.service
    destination: /etc/systemd/system/
  - source: /build/my-subreddit-instance/*
    destination: /var/www/my-subreddit-instance/

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
