version: 0.0
os: linux

files:
  - source: /nginx.conf
    destination: /etc/nginx/
  - source: /my-subreddit-instance.service
    destination: /etc/systemd/system/
  - source: /build
    destination: /usr/local/bin/my-subreddit-instance/
    pattern: "**"

hooks:
  ApplicationStop:
    - location: scripts/application_stop
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start
      timeout: 300
      runas: root
