version: 0.2

phases:
  install:
    runtime-version:
      dotnet: 8.0
    commands:
      - yum update -y
      - yum install nginx -y
      - yum install dotnet-sdk-8.0 -y
  pre_build:
    commands:

  build:
    commands:
      - dotnet publish -o /var/www/my-subreddit-instance

  post_build:
    commands:
# artifacts:
#   files:
#     - "**/*"
