version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - yum update -y
      # - yum install nginx -y

  pre_build:
    commands:
      - dotnet --version

  build:
    commands:
      - dotnet publish src/my-subreddit-instance.csproj -o build

  post_build:
    commands:
      - ls -la build
      - zip -r my-subreddit-instance.zip appspec.yml my-subreddit-instance.conf my-subreddit-instance.service scripts/ build/

artifacts:
  files:
    - "my-subreddit-instance.zip"
