version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - yum update -y
      - yum install nginx -y
  pre_build:
    commands:
      - dotnet --version
  build:
    commands:
      - dotnet publish -o /var/www/my-subreddit-instance

  post_build:
    commands:
# artifacts:
#   files:
#     - "**/*"
