#!/bin/bash
# dnf install -y aspnetcore-runtime-8.0
# yum install nginx -y
# export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true

cp /my-subreddit-instance.conf /etc/nginx/conf.d/
cp /my-subreddit-instance.service /etc/systemd/system/
cp /build/my-subreddit-instance/* /var/www/my-subreddit-instance/